
# NVIDIA
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Larger cursor for easier visibility at native (1.0) scale
env = XCURSOR_SIZE,36
env = HYPRCURSOR_SIZE,36
