# ───────────────────────────────────────
# First monitor ── Acer QG240Y (24")
# ───────────────────────────────────────
workspace = 1, monitor:desc:Acer Technologies QG240Y H3 1321022A93V01, default:true
workspace = 2, monitor:desc:Acer Technologies QG240Y H3 1321022A93V01
workspace = 3, monitor:desc:Acer Technologies QG240Y H3 1321022A93V01
workspace = 4, monitor:desc:Acer Technologies QG240Y H3 1321022A93V01

# ───────────────────────────────────────
# Second monitor ── Acer QG271 (27")
# ───────────────────────────────────────
workspace = 6,  monitor:desc:Acer Technologies QG271 TGJEE00885S8, default:true
workspace = 7,  monitor:desc:Acer Technologies QG271 TGJEE00885S8
workspace = 8,  monitor:desc:Acer Technologies QG271 TGJEE00885S8
workspace = 9,  monitor:desc:Acer Technologies QG271 TGJEE00885S8